# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/tm_Dronfa_xy/TM/CTM.srcs/sources_1/ip/blk_mem_masks_64bits/blk_mem_masks_64bits.xci
# IP: The module: 'blk_mem_masks_64bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/tm_Dronfa_xy/TM/CTM.srcs/sources_1/ip/blk_mem_masks_64bits/blk_mem_masks_64bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_masks_64bits'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/tm_Dronfa_xy/TM/CTM.srcs/sources_1/ip/blk_mem_masks_64bits/blk_mem_masks_64bits.xci
# IP: The module: 'blk_mem_masks_64bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/tm_Dronfa_xy/TM/CTM.srcs/sources_1/ip/blk_mem_masks_64bits/blk_mem_masks_64bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_masks_64bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
